### ISSUE TITLE
Last versionw working with HUR7.0

### ISSUE THREAD

**Issue by jgato** [borconi/WifiLauncherforHUR#19]
Hi there,
I have been using WifiLauncher and HUR5.x for years. With the new change I cannot manage to make it work.

Which component is supposed to created the hotspot? WifiLauncher? When I select in WifiLauncher to enable the hotspot, this just enables one hotspot I have in my mobile. I mean, a real hotspot I have on my mobile to share Internet connection to whatever other device. Should not create a different one? or, should this be done by HUR?

Thanks for the effort, I see again movement in both projects, which is cool.

**Comment by borconi** [comment]
New approach os different it uses network service discovery instead of IP addresses. As soon as both devices are on the same network they should find each other and AA will fire up. The tethering option will just enable the normal hotspot, yes. You can connect the cars unit to it and open HUR, that's all.

**Comment by jgato** [comment]
If I use the normal hotspot in my mobile, it tries to connnect. But the mobile shows and android auto error like not using compatible versions.

**Comment by jgato** [comment]
I have playing with different DPIs but connecting to USB. Which works seamless. Let me go to try.

**Comment by jgato** [comment]
Ok, I have been doing many different tests. I made it to work but... not sure how. It is like some kind of "race condition", or dependence in the order on how I make the connection.
It seems that the process that made it ok more times was: 
 1 - HUR not running on car
 2 - Create manually the hotspot in the mobile
 3 - Wait the car to connect the hotspot
 4 - Open HUR
 5 - Run the wifylauncher service
sometimes it works, sometimes not. 
When it works, I can enable/disable many times and it will work.
If I switch off the car, and re-start again... again it will hardly ever connect.
I have also tried disconnecting bluetooth, not sure if this also affects. Sometimes it me make think it is related. But again, I think there is one strange hidden condition.

**Comment by jgato** [comment]
I have tested the new versions. ummmm seems like it connects better, but still tricky.
I think it works, most of the time, if I switch on the car with HUR closed (important). Then in the mobile I run the service, the hotsspot. Wait the car to join the hotspot and open HUR. It works.
If I switch on the car with HUR already running, it will mostly fail.
There are sill some strange conditions depending on the running workflow.
