### ISSUE TITLE
Allow to execute even if Wi-Fi is connected

### ISSUE THREAD

**Issue by felipecrs** [borconi/WifiLauncherforHUR#21]
An option to allow Wi-Fi Launcher to execute even if Wi-Fi is connected and connection mode is set to Phone Hotspot.

![image](https://github.com/borconi/WifiLauncherforHUR/assets/29582865/f1061c5a-c4c1-4f72-a6b1-2627ace6cc7c)

My use case for the above is because where I live, there is no cell signal, and I have Access Points covering the entrance of my house.

My smartphone is capable of routing Wi-Fi too.

For my use case, it would be awesome if I did not have to disconnect Wi-Fi for the Wi-Fi launcher to work.

**Comment by felipecrs** [comment]
@borconi, I'm sorry to ping you directly, but:

1. Do you think it is possible?
1. Are you okay with this proposal?

If yes, I may try to send you a PR, even though I'm not an Android developer.

**Comment by borconi** [comment]
No it won't be as AA will bind itself to the WiFi network resulting in disconnection when the WiFi disconnects, hence WiFi Launcher waiting for the WiFi to get disconnected. Once you drive away from home and your phone is disconnected from the home network, it will start up AA just fine.

**Comment by felipecrs** [comment]
Ok, thank you then.

**Comment by felipecrs** [comment]
@borconi, I tried enabling WiFi on the mobile after AA is connected and then AA remains working fine.

I'm using a S24 Ultra.

Are you really sure this can't be lifted?

Maybe it works on some phones, and maybe a button to enable/disable this function would be nice.
