### ISSUE TITLE
MIUI 12 Wi-Fi Control Special App Access crashing loop on startup

### ISSUE THREAD

**Issue by gvillo** [borconi/WifiLauncherforHUR#5]
MIUI has an issue on his end and it's crashing when we are adding Wi-Fi Suggestions in Android 10 and up if Wi-Fi Control Special App Access is not granted.

**Solution**
Add a screen just for MIUI users to guide users to grant manually Wi-Fi Control Special App Access before trying to add a Wi-Fi Suggestion

In addition we should research if we could check if Wi-Fi Control Special App Access is granted, to display this screen for non-MIUI users too (if user dismissed it or deny access by mistake). This access must be granted in all cases.

**Workaround**
Grant Wi-Fi control Special App Access permissions before start it for the first time

**More Info**
https://forum.xda-developers.com/general/paid-software/android-4-1-headunit-reloaded-android-t3432348/post83563121#post83563121

**App version**
v3.1

**Devices Affected**
Xiaomi MIUI 12 
(We don't know if others MIUI versions are affected too)

**Comment by borconi** [comment]
Stupid MIUI...

Kind regards
Emil Borconi-Szedressy
Tel: +44-791-32-32-588 / +40-755-29-00-43

**Comment by gvillo** [comment]
Raised a bug in MI forums: https://c.mi.com/thread-3350895-1-1.html
Found a way to check if Wi-Fi Control is enabled it or not (https://issuetracker.google.com/issues/169471814 and reported a bug to Google)

New PR #6 with a lot of things!
